### ISSUE TITLE
Spaces in xtsAttributes in influx_write

### ISSUE THREAD

**Issue by JonasGutermuth** [dleutnant/influxdbr#11]
It is not possible to use tag values with spaces as value. Influxdb would allow this:

Influx line protocol allows spaces in tag values. It is not necessary to replace spaces with _. It is possible to use the backslash character \ to escape space, comma or =
https://docs.influxdata.com/influxdb/v1.2/write_protocols/line_protocol_reference/#special-characters

**Comment by dleutnant** [comment]
Thanks for spotting this! Are you preparing a PR?

**Comment by JonasGutermuth** [comment]
I prepared a PR. But I started to learn R one week ago. So my R skills are not very good. So there should be a better way to solve this. #12

**Comment by dleutnant** [comment]
Any help is greatly appreciated! So thanks for your contribution!

**Comment by JonasGutermuth** [comment]
I prepared a PR. But I started to learn R one week ago. So my R skills are not very good. So there should be a better way to solve this. #14

**Comment by dleutnant** [comment]
solved #14
