### ISSUE TITLE
./div : non-numeric argument to binary operator

### ISSUE THREAD

**Issue by xanderdunn** [dleutnant/influxdbr#15]
Windows 7
R 3.2.5
Installed the prepare_cran branch at 1c7d180937dca6d4d6d387528a2ba26b7bcb08d6

```
con<- influxdbr::influx_connection(scheme = "https", host = Sys.getenv("INFLUX_HOST"), port = 8086, user = "myuser", pass = Sys.getenv("INFLUX_PASSWORD"))
```
It successfully connects, then:

```
result <- influx_select(con = con, db = "mydb", field_keys = "*", measurement = "mymeasurement", group_by = "*", order_desc = TRUE, return_xts = FALSE)
```

It fails with:
```
Error in ./div : non-numeric argument to binary operator
Calls: source ... eval -> <Anonymous> -> map -> .Call -> .f -> as.POSIXct
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```

I'm trying to do an InfluxDB command like this: `SELECT * FROM mymeasurement`.  I want all the fields from the measurement.

However, I get the same output even when I specify a field key:
```
result <- influx_select(con = con, db = "mydb", field_keys = "mykey", measurement = "mymeasurement", group_by = "*", order_desc = TRUE, return_xts = FALSE)
```

I've double checked that `mymeasurement`, `mydb`, and the field key `mykey` all exist in the InfluxDB instance that I'm connected to.  They're populated and this works for me in [influxdb-python](https://github.com/influxdata/influxdb-python).

Is it because some of the fields are strings rather than numbers?  Specifically, the `mykey` field that I tested has string values.

**Comment by xanderdunn** [comment]
Using `influx_query`:
```
result <- influx_query(con = db, db = "mydb", query = "SELECT * FROM mymeasurement")
```

I get the same error, different warning:
```
Error in ./div : non-numeric argument to binary operator
Calls: source ... eval -> <Anonymous> -> map -> .Call -> .f -> as.POSIXct
In addition: Warning message:
In matrix(unlist(.x), nrow = length(.y)) :
  data length [306729] is not a sub-multiple or multiple of the number of rows [
61]
Execution halted
```

**Comment by xanderdunn** [comment]
When I select only a field that has float values, it works:
```
result <- influx_query(con = db, db = "mydb", query = 'SELECT "my_float_key"
FROM mymeasurement')
```

**Comment by dleutnant** [comment]
Thanks @xanderdunn for spotting and reporting this! Could you please install the recently pushed version [(c658b4a)](https://github.com/dleutnant/influxdbr/commit/c658b4abc86e1176ac5712e63560362de68b106b) and check whether the error still occurs?

**Comment by xanderdunn** [comment]
Many thanks for your help.

I updated to latest and I no longer get this error for string fields.
