### ISSUE TITLE
How to get point tags?

### ISSUE THREAD

**Issue by xanderdunn** [dleutnant/influxdbr#16]
Windows 7
R 3.5.2
Installed the prepare_cran branch at 1c7d180937dca6d4d6d387528a2ba26b7bcb08d6

When I have `return_xts = TRUE`, I get back an index that is the field's timestamp, and the fields requested, but there are no columns for tags.  Example query:
```
result <- influx_query(con = db, db = "bloomberg_weekly", query = 'SELECT "my_float_key"
FROM mymeasurement', return_xts = TRUE)
```
`xtsAttributes(results)` returns NULL.

When I use `return_xts = FALSE`, I get a tibble with an empty `series_tags` column:
```
 # A tibble: 7,532 x 6
   statement_id series_names      series_tags series_partial
          <int>        <chr>           <list>          <lgl>
1             0    measurem <tibble [0 x 0]>          FALSE
2             0    measurem <tibble [0 x 0]>          FALSE
3             0    measurem <tibble [0 x 0]>          FALSE
4             0    measurem <tibble [0 x 0]>          FALSE
5             0    measurem <tibble [0 x 0]>          FALSE
6             0    measurem <tibble [0 x 0]>          FALSE
7             0    measurem <tibble [0 x 0]>          FALSE
8             0    measurem <tibble [0 x 0]>          FALSE
9             0    measurem <tibble [0 x 0]>          FALSE
10            0    measurem <tibble [0 x 0]>          FALSE
```
The measurement here is called "measurem" and there were some non-empty field columns not shown.  

[influxdb-python](https://github.com/influxdata/influxdb-python) returns the tags as distinct columns alongside the field columns.

**Comment by dleutnant** [comment]
Could you please check the following query:
`result <- influx_query(con = db, db = "bloomberg_weekly", query = 'SELECT "my_float_key" 
FROM mymeasurement GROUP BY *', return_xts = FALSE)`

(only `GROUP BY *` clause added)

**Comment by xanderdunn** [comment]
Thanks very much for helping me.

Simply adding `GROUP BY *` works for me to get the tags as columns.
