### ISSUE TITLE
Error in bind_rows_(x, .id)

### ISSUE THREAD

**Issue by xanderdunn** [dleutnant/influxdbr#17]
Windows 7
R 3.5.2
prepare_cran installed at c658b4abc86e1176ac5712e63560362de68b106b

Getting a tibble of all fields in my database, where some are strings, some are floats, and some are ints:
```
result <- influx_query(con = con, db = "mydb", query = 'SELECT * FROM mymeasurement GROUP BY *', return_xts = FALSE)
```

I get this error:
```
Error in bind_rows_(x, .id) :
  Can not automatically convert from factor to numeric in column "myfloatkey".
Calls: source ... unnest_.data.frame -> lapply -> FUN -> bind_rows_ -> .Call
In addition: There were 50 or more warnings (use warnings() to see the first 50)

Execution halted
```

The trouble seems to be parsing the values in `myfloatkey`.

**Comment by xanderdunn** [comment]
Here are some actual values from `myfloatkey`:
```
12136.97391374
0.33866439
0.14968538
0.11619178
0.34972626
0.22924717
0.47832193
0.09910389
1.90216014
1.18194519
0.27418391
0.1086297 
1.55918611
0.17252949
1.04249313
-2.32209712
0.19202161
2.70440928
0.09369765
0.54899539
0.08216948
0.04680047
1.39969864
0.07696573
0.17433527
0.60271846
1.39394516
3.23225877
1.60824995
0.02966674
0.01986935
1.08324529
0.23111629
1.97756162
3.44260266
0.2812656 
0.40502124
-1.79684694
0.17129736
0.95202046
0.01761328
0.06368355
0.85127535
0.18128328
7.07237713
-2.05438581
```

The only abnormality I see is maybe the negative floats?

**Comment by dleutnant** [comment]
Thanks again @xanderdunn for spotting and reporting this! Could you please install the recently pushed version [025f1a](https://github.com/dleutnant/influxdbr/commit/025f1af2282b80a64a4de0e652618c87271b95b0) and check whether the error still occurs?

**Comment by xanderdunn** [comment]
Thanks!

On 025f1af2282b80a64a4de0e652618c87271b95b0, I no longer see the above error.  However, I do get this:
```
Error: Each variable must be a 1d atomic vector or list.
Problem variables: 'mykey'
Execution halted
```

I checked that executing the same query in influxdb-python worked.

**Comment by xanderdunn** [comment]
Some example values from `mykey`:
```
NaN
NaN
NaN
0.686884
NaN
NaN
NaN
13.770723
0.153481
NaN
NaN
NaN
NaN
1.082575
NaN
NaN
2.705221
```

Perhaps it's because my data have missing values?

**Comment by dleutnant** [comment]
Could you please post the code to create the xts you've uploaded?

**Comment by dleutnant** [comment]
@xanderdunn Ignore my xts request.  The error occurs because mykey data has missing values (NULL) which tibbles cannot represent. Fixed with [e5646e](https://github.com/dleutnant/influxdbr/commit/e5646ee57def54bfeec8dc3e4d210d00e87dffd6)
