### ISSUE TITLE
Write a different tag value for every element of an xts

### ISSUE THREAD

**Issue by xanderdunn** [dleutnant/influxdbr#19]
Based on my experimentation with `xtsAttributes` and looking at the [documentation](https://cran.r-project.org/web/packages/xts/vignettes/xts.pdf), it looks like setting attributes on an xts are global attributes for all values in the matrix?  

What I'd like to do is be able to set `xtsAttributes(my_xts) <- (tag_key = my_tags)`, where `nrows(my_xts) == nrows(my_tags)` so that every item in `my_xts` has a different value for the same `tag_key`.

This is easy to do in influxdb-python where the column of a data frame can be specific as a tag column in the `influx_write` function.

**Comment by dleutnant** [comment]
Yeah, that would be great! We therefore need to parse a `data.frame` to influxdb's line protocol and modify `influx_write`.  

It must be further specified, which columns are fields and which are tags (optionally, a datetime column, too)

**Comment by dleutnant** [comment]
I'm closing this issue and opening the #20
