### ISSUE TITLE
[BUG] Double Quote Inclusion Around Measurement Names

### ISSUE THREAD

**Issue by ckatsulis** [dleutnant/influxdbr#22]
Is it possible for you to include a double quote around the names of `measurements`?  When the measurement has special characters, the string needs to be sent as a literal, in which case I have to wrap all of the `measurements` with:
`paste0('\"',x,'\"')`

I don't believe this causes issues for `measurements ` without this need, so it would just be a relief in the case where .!@#$%^&*(/ are used in a name.

**Comment by dleutnant** [comment]
I'm not quite sure if I get you right (s. Line Protocol Tutorial: "Do not double or single quote measurement names, tag keys, tag values, and field keys. It is valid Line Protocol but InfluxDB assumes that the quotes are part of the name."). Therefore, could you please propose a PR with all relevant code changes? Thanks!

**Comment by ckatsulis** [comment]
When it comes to changes, I'm pretty useless :)

## Measurements with Special Characters
### Erroneous Queries
```r
> influx_select(con, "dbdata", measurement = "tag/value", field_keys = "*", limit = 100L)[[1]]
NULL
Warning message:
http: error parsing query: found /, expected ; at line 1, char 18 

> influx_select(con, "dbdata", measurement = 'tag/value', field_keys = "*", limit = 100L)[[1]]
NULL
Warning message:
http: error parsing query: found /, expected ; at line 1, char 18 

> influx_select(con, "dbdata", measurement = "'tag/value'", field_keys = "*", limit = 100L)[[1]]
NULL
Warning message:
http: error parsing query: found tag/value, expected identifier at line 1, char 14 

> influx_select(con, "dbdata", measurement = "\'tag/value\'", field_keys = "*", limit = 100L)[[1]]
NULL
Warning message:
http: error parsing query: found tag/value, expected identifier at line 1, char 14 

> influx_select(con, "dbdata", measurement = sQuote(dQuote("tag/value")), field_keys = "*", limit = 100L)[[1]]
NULL
Warning message:
http: error parsing query: found â€˜, expected identifier at line 1, char 15 

> influx_select(con, "dbdata", measurement = sQuote("tag/value"), field_keys = "*", limit = 100L)[[1]]
NULL
Warning message:
http: error parsing query: found â€˜, expected identifier at line 1, char 15 

> influx_select(con, "dbdata", measurement = dQuote("tag/value"), field_keys = "*", limit = 100L)[[1]]
NULL
Warning message:
http: error parsing query: found â€œ, expected identifier at line 1, char 15 
```
### Working Queries
```r
> influx_select(con, "dbdata", measurement = '"tag/value"', field_keys = "*", limit = 100L)[[1]]
```
### Suggested Fix
My guess is that because measurement names can have special characters in influx (e.g. `/` as I do in the above example), and those require to be double quoted in the line protocol.  However, tag key values that have special characters require single quoting in the query line protocol.  I don't know exactly why that is the case, but I will look on the boards and ask Dix if there isn't anything there.
https://github.com/influxdata/influxdb/issues/6011


## Tag Keys with Special Characters
### Erroneous Queries
```r
> influx_select(con, "dbdata", measurement = "data", field_keys = "L1BP,L1BV,L1AP,L1AV", where = 'symbol='tag/value' and time >= now() - 2d', limit = 100L)[[1]]
```
### Working Queries
```r
> influx_select(con, "dbdata", measurement = "data", field_keys = "L1BP,L1BV,L1AP,L1AV", where = "symbol='tag/value' and time >= now() - 2d", limit = 100L)
### AND
> influx_select(con, "dbdata", measurement = "data", field_keys = "L1BP,L1BV,L1AP,L1AV", where = 'symbol::tag=\'tag/value\' and time >= now() - 2d', limit = 100L)
### AND
influx_select(con, "dbdata", measurement = "data", field_keys = "L1BP,L1BV,L1AP,L1AV", where = 'symbol=\'tag/value\' and time >= now() - 2d', limit = 100L)[[1]]
```

Seems it's much easier to find a working set of quotes for your package when dealing with tag values with special characters.

**Comment by dleutnant** [comment]
Measurements are now double quoted in `influx_select`. However, some of the errors you've got are more related to R's `useFancyQuotes` option.
> http: error parsing query: found â€œ, expected identifier at line 1, char 15

Setting `option("useFancyQuotes" = FALSE)` yields to correct results. 
Current [dev version e498186](https://github.com/dleutnant/influxdbr/commit/e498186f8d9f7019415fee4c4abc2f08784d4514) takes care of this.

Let me know if this works out.
