### ISSUE TITLE
404 Error on influxdbr_connection

### ISSUE THREAD

**Issue by ktrev** [dleutnant/influxdbr#24]
Hi,

After installing influbdbr from CRAN I am getting the following error

> Warning in influxdbr::influx_connection(host = "localhost", port = 8086) :
  404 page not found Warning: Error in influxdbr::influx_connection: Influx connection failed with HTTP status code 404

In another machine, I have influxdbr installed with devtools. It works fine.

**Comment by dleutnant** [comment]
I need more information to get into your issue. 

- How about your sessioninfo (both machines)?  --> `sessionInfo()`
- Where does your influxdb server instance live?  On localhost? Another machine? Please make sure to connect to the right address.
- Which server version of InfluxDB? 
- Does ping work?

**Comment by dleutnant** [comment]
Could you please check your `path` argument of `influx_connection`? Did you try `path="/"` or `path=""`?

**Comment by ktrev** [comment]
The db exists
I am not using path argument.
The same code works fine in the older version of influxdbr on another server.
My influxdb instance is on localhost
InfluxDB version 1.2
Ping works

**Comment by dleutnant** [comment]
Please use the CRAN version on every machine. Specifying the `path` argument is supported in the newest package version.  
If your instance is not running behind a proxy, please set path to `path="/"` or `path=""`.

**Comment by ktrev** [comment]
Tried with path. Still same error

**Comment by dleutnant** [comment]
Could you please paste your `sessionInfo()` of both machines?

**Comment by ktrev** [comment]
I removed the package and installed it again. Now it is working.
