### ISSUE TITLE
Would it be possible to add more precision values

### ISSUE THREAD

**Issue by AndreasBraun2015** [dleutnant/influxdbr#26]
Hello

I like your influxdbr package, many thanks for sharing it!

I try to store daily time series into influxdb using your package, but the precision for daily (d) is missing. Would it be possible to add this to your package?

https://docs.influxdata.com/influxdb/v1.3/query_language/spec/#durations

Many thanks!

Best,
Andreas

**Comment by dleutnant** [comment]
Hi Andreas,
'daily' reflects a duration and not a precision. Please check the query string parameter `epoch`/`precision` for the [/query](https://docs.influxdata.com/influxdb/v1.3/tools/api/#query) and [/write](https://docs.influxdata.com/influxdb/v1.3/tools/api/#write) api endpoints. 

However, storing daily time series should work in any case. Did you already try this? Did you see anything unexpected?

Cheers,
Dominik

**Comment by AndreasBraun2015** [comment]
Hi Dominik,

I tried to write a time series (xts) consisting of monthly data:

1978-01-01 | 11.50
1978-02-01 | 11.56
1978-03-01 | 11.61

If I read the data back, I get : 
1970-01-01 00:48:42 | 11.50
1970-01-01 00:49:13 | 11.56
1970-01-01 00:49:41 | 11.61

I think the reason is that "InfluxDB assumes that timestamps are in nanoseconds if you do not specify precision". Or do I have to convert the date index in a special way before writing to the database?

**Comment by dleutnant** [comment]
Which class do you use to represent the index of your daily data? I guess it's rather `date` than `POSXIct`? We may need a different way of parsing date time classes other than `POSIXct`. But if you'd convert your class to `POSIXct` beforehand (and just ignore the sub-day accuracy), you could store daily series data, too. Also you could aggregate by time according to the InfluxQL in the query command. Does this work for you?

**Comment by dleutnant** [comment]
@AndreasBraun2015 Any more support need here?

**Comment by AndreasBraun2015** [comment]
No, thank you. I will test it with other time formats than Date. Best regards Andreas

**Comment by dleutnant** [comment]
Just let me know if you need help with this.
