### ISSUE TITLE
tags not supported on influx_write

### ISSUE THREAD

**Issue by jgibson12** [dleutnant/influxdbr#33]
Without supporting tags, only the simplest of database could be used.

**Comment by jgibson12** [comment]
This was meant for influxdbr and I see now that influxdbr2 exists and has been forked from influxdbr

**Comment by dleutnant** [comment]
I assume you mean tags within data.frames. The dev version supports writing data.frames, which includes tags per time stamp. Checkout the manual. Otherwise tags of xts objects were supported at the first place.

**Comment by dleutnant** [comment]
Is the `influx_write` function in the dev version helping you? (I'm preparing a next cran release)
