### ISSUE TITLE
 influx_ping - error handling when connection is refused/down

### ISSUE THREAD

**Issue by jgibson12** [dleutnant/influxdbr#34]
Influx_ping gives an error message printed when there is no connection but status still = 204. There is also nothing in the connection that indicates it has gone down either.

At least the status from influx_ping should change so connections can be monitored accurately.

**Comment by dleutnant** [comment]
Thanks! Could you please get me some code to make it reproducible?

**Comment by jgibson12** [comment]
conn <<- influxDbConn <- influxdbr::influx_connection(host = INFLUXDB_HOST)

testVal <- influx_ping(conn)
print(testVal[[1]]$status)
## status is 204

## STOP - shutdown INFLUX DB service - sudo service influxdb stop
## execute lines again
testVal <- influx_ping(conn)
print(testVal[[1]]$status)
## status still 204 but connection is down

**Comment by dleutnant** [comment]
OK, I see what you mean. The following should work for you:

`testVal <- tryCatch(influx_ping(conn), error = function(e) {message(e);return(NULL)})`

Then you could test with `is.null(testVal)`.
