### ISSUE TITLE
Support of HTTPS (with self-signed cert)

### ISSUE THREAD

**Issue by ColinLeverger** [dleutnant/influxdbr#36]
I use a self-signed https cert on a server of mine, and it is not accepted by influxdbr.
I tried to configure curl with the following link: https://stackoverflow.com/questions/22048703/rcurl-and-self-signed-certificate-issues

# How to reproduce
## Code
```
# Install lib
install.packages("influxdbr")
install.packages("httr")

# Load lib for curl
library(httr)
# Configure your path for the cert
config(cainfo="C:some_path")

# Load libs
library(dplyr)
library(influxdbr)
library(xts)

# Create connection object 
con <- influx_connection(scheme = c("https"), host = "some_ip", port = 8086, 
                         user = "some_user", pass = "some_pass", 
                         path = "/", group = NULL,
                         verbose = TRUE)
```
## Error
```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.
```

**Comment by dleutnant** [comment]
Strange. We've got our InfluxDB with https running (and of course a working communication between R and InfluxDB).
Did you verify your HTTPS setup ([link](https://docs.influxdata.com/influxdb/v1.3/administration/https_setup/#setup-https-with-a-self-signed-certificate))?

**Comment by dleutnant** [comment]
My first guess is that the relevant curl options are not interpreted.
Could you please submit a test ping with your settings and specifying your cainfo as {httr} option?

#submit test ping
```
response <- httr::GET(
  url = "",
  scheme = "https",
  hostname = "your_ip",
  port = 8086,
  path = "/ping",
  # HERE CAINFO as httr option
)
```

**Comment by dleutnant** [comment]
also, maybe it helps to set the cainfo path [globally](https://stackoverflow.com/questions/28557831/httr-package-ssl-certificate-error-ssl3-get-server-certificate):

`httr::set_config(config(cainfo = 'C:some_path'))`

**Comment by ColinLeverger** [comment]
Thanks for your quick reply. I confirm that setting the parameter globally works perfectly fine. Now we could either:

1. Document this solution in the README.md file,
2. Code a boolean parameter in the ```influx_connection``` method, e.g ```selfsigned_cert: Boolean```, which wrap this httr configuration inside the function.

I am willing to code/pull request, but my knowledge in R developing is relatively limited...

What worked for me:
```
httr::set_config(config(ssl_verifypeer = FALSE))
```
It was more convenient than setting the cainfo.

**Comment by dleutnant** [comment]
Nice! Thanks! I think it would be straightforward to extend `influx_connection` with `...` and pass those values to the `httr::GET` method. Of course, the connection object must contain those values which are then interpreted at `httr::GET` and `httr::POST` statements in 

- [ ] `influx_ping`,
- [ ] `influx_query`,
- [ ] `influx_post` and
- [ ] `influx_write`.

With this approach you could either go the "global" or the "local" way.

**Comment by ColinLeverger** [comment]
All right then, do you need some help for that?

**Comment by dleutnant** [comment]
Yes! I'm going to commit the changes after some internal checks and would be happy if you could test the modified version then.

**Comment by dleutnant** [comment]
Would you like to give the dev version a try?

**Comment by dleutnant** [comment]
@ColinLeverger Did you have the chance to test the dev version?

**Comment by ColinLeverger** [comment]
Hello @dleutnant, sorry to answer so late- I replied to an email I received about this thread, and my answer did not appear there for some reason... 
I just told you in this "lost email" that I was not sure of the procedure to test the dev version, do you have any guidelines/docs?

**Comment by dleutnant** [comment]
No worries. I suggest to download the dev version via

```r
# install.packages("remotes")
remotes::install_github("dleutnant/influxdbr@dev")
```

Afterwards, please use `influxdbr::influx_connection` with the required `curl_options` (s. help).

**Comment by ColinLeverger** [comment]
It works for me with:

```
curl_options = httr::config(ssl_verifypeer = FALSE, ssl_verifyhost = FALSE)
```
All good, thanks! :-)

**Comment by dleutnant** [comment]
OK, thanks!
