### ISSUE TITLE
Error: 'imap_dfr' is not an exported object from 'namespace:purrr'

### ISSUE THREAD

**Issue by caxelrud** [dleutnant/influxdbr#38]
I am using R version 3.4.0.
I installed using devtools::install_github("dleutnant/influxdbr@dev"). 
Testing the example from https://github.com/dleutnant/influxdbr , I got the following when executing the following statement:
influx_write(con = con, db = "mydb",x = df_data,time_col = "time", tag_cols = c("info", "UnitTesting", "n"),measurement = "sampledata_df")
Error: 'imap_dfr' is not an exported object from 'namespace:purrr'

**Comment by dleutnant** [comment]
Do you have the most recent {purrr} package?

Von meinem iPhone gesendet

Am 26.12.2017 um 21:51 schrieb caxelrud <notifications@github.com<mailto:notifications@github.com>>:


I am using R version 3.4.0.
I installed using devtools::install_github("dleutnant/influxdbr@dev").
Testing the example from https://github.com/dleutnant/influxdbr , I got the following when executing the following statement:
influx_write(con = con,

  *

         db = "mydb",


  *

         x = df_data,


  *

         time_col = "time", tag_cols = c("info", "UnitTesting", "n"),


  *

         measurement = "sampledata_df")


Error: 'imap_dfr' is not an exported object from 'namespace:purrr'

**Comment by dleutnant** [comment]
Issue solved?

**Comment by caxelrud** [comment]
My installation had purrr version 0.2.2 (I believe from using devtools::install_github("dleutnant/influxdbr"))
I used devtools::install_github("tidyverse/purrr").
Now the version is 0.2.4.900 and the influxdbr is working fine.

**Comment by dleutnant** [comment]
Ok, thanks. I‘ll add the required version to the description file.

**Comment by dleutnant** [comment]
fixed in 9245b5da7b0cc5260bf2444daaf244d1ba2aeb8e
