### ISSUE TITLE
Error while trying to write data from R to InfluxDB

### ISSUE THREAD

**Issue by aruku333** [dleutnant/influxdbr#39]
I am trying to write data into Influx DB from R using InfluxdbR package but facing some issues. The connection is successful and I was able to ping too. Can you please help advice on this. Is this happening as the latest version of dplyr is not supportive?

Data
Start_date      val   site 
2017-01-01 23.45 US 
2017-01-02 26.78 US 
2017-01-03 28.98 US

Code:  

`> library(ggplot2) library(xlsx) library(ggplot2) library(forecast) library(lubridate) library(doBy) library(plyr) library(stringr) library(tidyr) library(dplyr)con <- influx_connection(host = "host", user ="user", pass = "pass",port = 8086)influxdbr::influx_write(con = con,               db = "db1",              x = data1,              time_col = "Start_date", tag_cols = "site",measurement = "dim1")
`

Error:Error: 'rename_all' is not an exported object from 'namespace:dplyr'

**Comment by dleutnant** [comment]
dplyr >= 0.7.0 is required. Which version do you have installed?

**Comment by aruku333** [comment]
I think that's the problem. I have 0.5.0 installed. Let me try it and will let you know.Thanks much!

**Comment by dleutnant** [comment]
Issue solved?

**Comment by aruku333** [comment]
Yes, Thanks. The version is the issue.
