### ISSUE TITLE
When using the influxdbr::influx_write function, an error is returned if the xts is not entirely numerical

### ISSUE THREAD

**Issue by williampeterpaul** [dleutnant/influxdbr#4]
`  if ((use_integers == TRUE) & (all(xts == floor(xts)))) {` ./R/influxdb.R:635

Causes the error: 
**Error in floor(xts) : non-numeric argument to mathematical function**

Current fix I have found is this
`  if ((use_integers == TRUE) & is.numeric(xts)) {
    if(all(xts == floor(xts))) {`

however it may not be ideal, as I am relatively new to R code

**Comment by dleutnant** [comment]
Thanks @williampeterpaul for your contribution. I'm planning to release an updated version of the influxbdr package by March (also to CRAN). I'll have a look at your proposal to tackle the error you've found.

**Comment by dleutnant** [comment]
PR is now integrated in [dleutnant/prepare_cran](https://github.com/dleutnant/influxdbr/tree/prepare_cran)
