### ISSUE TITLE
influx_query return value

### ISSUE THREAD

**Issue by cyiannaki** [dleutnant/influxdbr#41]
Hi dleutnant,

When the "influx_query" function tries to return "list_of_result" with return_xts = F, I get the following error:
         Error in as.POSIXct.default(rownames(oneMinData), tz = "UTC") : 
         do not know how to convert 'rownames(oneMinData)' to class “POSIXct”

I have checked the contents of "list_of_result" and all is correct."list_of_result" can be manually assigned to another variable but return does not work. rownames(oneMinData) is null. I am not sure why it's trying to convert to as.POSIXct?

Many thanks.

**Comment by dleutnant** [comment]
can you file an reproducible example?

**Comment by cyiannaki** [comment]
One small detail, the older version of your package did not have this issue.

Below is the code:

fullQuery <-  "select * from AUDUSD where time >=  1470009600000000000"
influx_query(con, "SYMBOLS", fullQuery, timestamp_format = "n", return_xts = F)

This is a screenshot of the database:

![influx](https://user-images.githubusercontent.com/10268607/35964494-cec03e8c-0caf-11e8-8196-e2688c3d0a72.jpeg)

**Comment by dleutnant** [comment]
> the older version of your package did not have this issue.

Which one? Which version do you now use?

> timestamp_format = "n"

Nanosecond precision is currently not supported (see #35). Please set to milisecs. 

Does the error still occur?

**Comment by cyiannaki** [comment]
I cannot remember the older version number.
Current Version: 0.14.3.9000
Changing timestamp_format to ms made no difference. I have only added this parameter while trying to get things to work.
As previously mentioned, the data is retrieved correctly within the influx_query function. It only prompts that error as soon as the return(list_of_result) is executed. 

Do you think its worth trying the same code on another pc?

Thanks again.

**Comment by dleutnant** [comment]
can you please install the latest version from CRAN ?

**Comment by cyiannaki** [comment]
Current Version: 0.14.2
It still does not work.

**Comment by dleutnant** [comment]
I can't reproduce the example.
The error says: 
> as.POSIXct.default(rownames(oneMinData), tz = "UTC")

Within the package, there is only one as.POSIXct line of code, which has tz = "GMT". So, where does the "UTC" come from?

Also, 
> oneMinData

makes me assume that there is something else going on.  There is no index column coded called "oneMinData". 

Did you change anything of the code? Maybe you have a special influx_query function? Did you restart your rsesssion after the CRAN updates?

**Comment by dleutnant** [comment]
Could you show me a screenshot (of your terminal)of the following query?

`select * from AUDUSD where time >= 1470009600000000000 limit 10`

**Comment by cyiannaki** [comment]
It seems that UTC is the default value as shown in the documentation: ?as.POSIXct.default
I have tried Sys.setenv(TZ="GMT") but it made no difference.
I have also tried running the same code on another machine and again it prompted me with the same error.

oneMinData is the variable name which I provided to store the return value from influx_query.
_oneMinData <- influx_query(con, "SYMBOLS", fullQuery, timestamp_format = "n", return_xts = F)_

Its kind of hard to say if there is an issue with my code since the function does get the data correctly and just fails to return it. I did indeed restart R (made sure no R processes where still running) after I installed from cran. 

![influx2](https://user-images.githubusercontent.com/10268607/35986118-1aa6493c-0cf0-11e8-89da-9aba7b8086c1.jpeg)

and some progress....when I add limit 10 it works!!!!
_fullQuery <- "select * from AUDUSD where time >= 1470009600000000000 limit 10"_

![influx3](https://user-images.githubusercontent.com/10268607/35986274-80a92e84-0cf0-11e8-89f7-3e75aaeafad9.jpeg)

If i set the limit to 100000 or remove it from the statement then I get this:
Error in as.POSIXct.default(rownames(oneMinData), tz = "UTC") : 
  do not know how to convert 'rownames(oneMinData)' to class “POSIXct”

When I run the below statement, it still retrieves the data but once the return statement is executed, it shows the same error.
_fullQuery <- "select * from AUDUSD where time >= 1470009600000000000"_

![influx4](https://user-images.githubusercontent.com/10268607/35986885-334d5172-0cf2-11e8-9f6d-e9480ed1592a.jpeg)

**Comment by dleutnant** [comment]
This is interesting. Can you reproduce the behaviour with R GUI (just to make sure RStudio is OK)...

**Comment by cyiannaki** [comment]
I have given it a go in the R GUI and I get the same issue. I'll give this more thought and let you know if I manage to find a resolution.

**Comment by dleutnant** [comment]
OK...

**Comment by dleutnant** [comment]
Any updates on this issue?

**Comment by cyiannaki** [comment]
Yes it has been resolved. If I remember correctly, there was some redundant code that was causing issues when I was running debug. Thank you for all the help.
