### ISSUE TITLE
Select all data from more than one measurement

### ISSUE THREAD

**Issue by nachti** [dleutnant/influxdbr#44]
Would be nice to support multiple FROM
See https://docs.influxdata.com/influxdb/v1.4/query_language/data_exploration/
Example 6: Select all data from more than one measurement
Fixed it in dev branch #43

**Comment by dleutnant** [comment]
Thanks!
Actually, as your commit already suggests, "multiple FROM" is per default supported.
Just change your `measurement` to `paste(measurement, collapse = ", ")` whereas `measurement` represents an atomic vector of characters.

**Comment by nachti** [comment]
Your suggestion is just works if `rp` is `NULL`. Try it for non-null rp and you'll see what's happening. Therefore I added the code at the right position in the function. I also think that a character vector is more intuitive for `measurement`.

**Comment by dleutnant** [comment]
> I also think that a character vector is more intuitive for `measurement`.

I agree on that.
Thanks!
