### ISSUE TITLE
Handling Empty Query Results

### ISSUE THREAD

**Issue by ktrev** [dleutnant/influxdbr#46]
`queryiOS <- paste0("SELECT COUNT(DISTINCT userid) FROM forever WHERE source = 'iOS' AND host ='",host,"'")
iOSCount <- influxdbr::influx_query(con = con, 
					 db = influxDB$dbName, 
					 query = queryiOS,
					 simplifyList = TRUE)`

The count is 0.  But instead of showing ) it is throwing the following error

> Error in statement_id:time : NA/NaN argument

How to handle empty results here?

**Comment by dleutnant** [comment]
if you set `return_xts = FALSE`, do you get the following warning:

`In .f(.x[[i]], ...) : no series returned`

?

**Comment by dleutnant** [comment]
As far as I know, if count is 0 an empty result is returned:
`{
    "results": [
        {
            "statement_id": 0
        }
    ]
}`

In the current development version, empty query results are now set to `NULL` which allows `is.null` checks. Hope this helps.
