### ISSUE TITLE
reading data from influxDB in TICK stack through chronograph

### ISSUE THREAD

**Issue by sarah-ewing** [dleutnant/influxdbr#50]
I am trying to use this package to access the influxDB at the heart of a TICK stack.

I can not get influx_query or influx_select to run without throwing a:

Error: lexical error: invalid char in json text.
                                       <!DOCTYPE html><html> <head> <m
           (right here) ------^

con <- influx_connection(scheme = "http", 
                         host = "10.8.36.2XX",
                         port = 8888, ##chronograph port ? data engineer says I can not access influx directly?
                         user = "XXXX", 
                         pass = "XXXX", 
                         path = "/var/lib/~",
                         verbose = TRUE, 
                         config_file = "~/.influxdb.cnf", 
                         curl_options = NULL)

fs_values <- influxdbr::influx_select(con = con,
                                      db = "xxx",
                                      field_keys = "price.close",
                                      measurement = "price",
                                      limit = 100,
                                      return_xts = FALSE)

result <- influx_query(
  con = con,
  db = "xxx",
  query = 'select * from xxx.autogen.price;',
  return_xts = FALSE, 
  simplifyList = FALSE
)

**Comment by dleutnant** [comment]
What does `influxdbr::influx_ping(con = con)` show you?

**Comment by sarah-ewing** [comment]
> influxdbr::influx_select(con = con)
Error in paste("SELECT", field_keys, "FROM", measurement) : 
  argument "field_keys" is missing, with no default

**Comment by dleutnant** [comment]
What does `influxdbr::influx_ping(con = con)` show you?

**Comment by sarah-ewing** [comment]
sry. Haven't had coffee yet.

> influxdbr::influx_ping(con = con)
# A tibble: 1 x 12
  status version headers.accept.… headers.cache.c… headers.content… headers.content… headers.etag headers.last.mo…
   <int> <fct>   <chr>            <chr>            <chr>            <chr>            <chr>        <chr>           
1    200 HTTP/1… bytes            public, max-age… gzip             text/html; char… "\"34316132… Wed, 06 Feb 201…
# … with 4 more variables: headers.vary <chr>, headers.x.chronograf.version <chr>, headers.date <chr>,
#   headers.content.length <chr>

**Comment by dleutnant** [comment]
Could you please insert the result from `as.list(influxdbr::influx_ping(con))`?

**Comment by sarah-ewing** [comment]
> as.list(influxdbr::influx_ping(con))
$status
[1] 200

$version
[1] HTTP/1.1
Levels: HTTP/1.1

$headers.accept.ranges
[1] "bytes"

$headers.cache.control
[1] "public, max-age=3600"

$headers.content.encoding
[1] "gzip"

$headers.content.type
[1] "text/html; charset=utf-8"

$headers.etag
[1] "\"34316132916\""

$headers.last.modified
[1] "Wed, 06 Feb 2019 20:40:00 GMT"

$headers.vary
[1] "Accept-Encoding"

$headers.x.chronograf.version
[1] "1.7.7"

$headers.date
[1] "Thu, 07 Feb 2019 15:01:42 GMT"

$headers.content.length
[1] "258"

**Comment by dleutnant** [comment]
OK, this is the result from chronograph. 
> port = 8888, ##chronograph port ? data engineer says I can not access influx directly?

You can access influx directly. Please have a look here:

https://docs.influxdata.com/influxdb/v1.7/administration/config/#http

If your data engineer didn't change the default config, you could try and check if you reach your InfluxDB instance at port 8086.

**Comment by sarah-ewing** [comment]
They are not letting me access influx directly. 8086 results in a "404 page not found."  Thank you for your time and helping me to troubleshoot this. Have a great day.

**Comment by dleutnant** [comment]
Did you try to use the default `path=/`?

**Comment by sarah-ewing** [comment]
> con <- influx_connection(scheme = "http", 
+                          host = "10.8.36.xxx",
+                          port = 8086, ## 8086 is the INFLUXDB and 8888 is chronograph
+                          user = "XXX", 
+                          pass = "xxx", 
+                          path = "/",
+                          verbose = TRUE, 
+                          config_file = "~/.influxdb.cnf", 
+                          curl_options = NULL)
[1] "http://10.8.36.xxx:8086/ping"
Success: (204) No Content

**Comment by dleutnant** [comment]
This looks good.

**Comment by sarah-ewing** [comment]
SO then the influx_select is incorrect?

> con <- influx_connection(scheme = "http", 
+                          host = "10.8.36.xxx",
+                          port = 8086, ## 8086 is the INFLUXDB and 8888 is chronograph
+                          user = "XXXX", 
+                          pass = "xxxx", 
+                          path = "/",
+                          verbose = TRUE, 
+                          config_file = "~/.influxdb.cnf", 
+                          curl_options = NULL)
[1] "http://10.8.36.xxx:8086/ping"
Success: (204) No Content
> 
> as.list(influxdbr::influx_ping(con))
$status
[1] 204

$version
[1] HTTP/1.1
Levels: HTTP/1.1

$headers.content.type
[1] "application/json"

$headers.request.id
[1] "91d5ebac-2aec-11e9-8017-0050fffffff7b"

$headers.x.influxdb.build
[1] "OSS"

$headers.x.influxdb.version
[1] "1.7.3"

$headers.x.request.id
[1] "91d5ebac-2aec-11e9-8017-0050fffffff7b"

$headers.date
[1] "Thu, 07 Feb 2019 15:25:15 GMT"

> 
> fs_values <- influxdbr::influx_select(con = con,
+                                       db = "db",
+                                       field_keys = "price.close",
+                                       measurement = "price",
+                                       limit = 100,
+                                       return_xts = FALSE)
Warning message:
In .f(.x[[i]], ...) : no series returned

**Comment by dleutnant** [comment]
> SO then the influx_select is incorrect?

I think the query statement is fine. 

Did you double check your field_keys (`influxdbr::show_field_keys(con, db = "db", measurement = "price")`)?

**Comment by sarah-ewing** [comment]
influxdbr::show_field_keys(con = con, db = "db", measurement = "price")
Error in .f(.x[[i]], ...) : object 'fieldKey' not found
In addition: Warning message:
In .f(.x[[i]], ...) : no series returned

**Comment by dleutnant** [comment]
Could you please double check your measurement (`influxdbr::show_measurements(con, db = "db")`)?

**Comment by sarah-ewing** [comment]
influxdbr::show_measurements(con, db = "tsmm")
Error in .f(.x[[i]], ...) : object 'name' not found
In addition: Warning message:
In .f(.x[[i]], ...) : no series returned

**Comment by dleutnant** [comment]
Well, how about your database (`influxdbr::show_databases(con)`)?

**Comment by sarah-ewing** [comment]
> influxdbr::show_databases(con = con)
# A tibble: 4 x 1
  name     
  <chr>    
1 _internal
2 db     
3 test1    
4 sample   
> influxdbr::show_measurements(con = con, db = "db")
Error in .f(.x[[i]], ...) : object 'name' not found
In addition: Warning message:
In .f(.x[[i]], ...) : no series returned

**Comment by dleutnant** [comment]
This looks great. Now you can pick one of those databases and start querying.

E.g. `influxdbr::show_measurements(con, db = "test1")`

**Comment by sarah-ewing** [comment]
There is still nothing in the db, unless I query _internal:

> influxdbr::show_measurements(con = con, db = "db")
Error in .f(.x[[i]], ...) : object 'name' not found
In addition: Warning message:
In .f(.x[[i]], ...) : no series returned
> influxdbr::show_measurements(con = con, db = "test1")
Error in .f(.x[[i]], ...) : object 'name' not found
In addition: Warning message:
In .f(.x[[i]], ...) : no series returned
> influxdbr::show_measurements(con = con, db = "sample")
Error in .f(.x[[i]], ...) : object 'name' not found
In addition: Warning message:
In .f(.x[[i]], ...) : no series returned
> influxdbr::show_measurements(con = con, db = "_internal")
# A tibble: 12 x 1
   name          
   <chr>         
 1 cq            
 2 database      
 3 httpd         
 4 queryExecutor 
 5 runtime       
 6 shard         
 7 subscriber    
 8 db1_cache    
 9 db1_engine   
10 db1_filestore
11 db1_wal      
12 write

**Comment by dleutnant** [comment]
From my perspective, the databases do not contain any measurements.

**Comment by dleutnant** [comment]
You could test your setup and write dummy data as described here:
https://github.com/dleutnant/influxdbr#write-data

**Comment by sarah-ewing** [comment]
Thank you for your help.  I think the main problem was that the data engineer told me 'db' was populated - but only '_internal' was. Again thank you so much for your time.

**Comment by dleutnant** [comment]
You're welcome!
