### ISSUE TITLE
Add progress bar on writes

### ISSUE THREAD

**Issue by vspinu** [dleutnant/influxdbr#51]
I am struggling with big data writes at the moment. They take a lot of memory and are extremely slow. A progress bar and optionally an expected remaining time would be useful.

**Comment by dleutnant** [comment]
Thanks for your comment. Could you please provide some timings and info about data dims? What do you mean by 'extremely' slow?

**Comment by vspinu** [comment]
I will investigate and will be back with you.

**Comment by dleutnant** [comment]
I just stumbled across the [tweet](https://twitter.com/henrikbengtsson/status/1101709349607497728) from @HenrikBengtsson, in which he questions some details about progress bars.

- when?
- shld end user be able to enable/disable them?
- what about nested fcns with progress output?
- accessibility/screen readers?

@vspinu Are you aware of any resource addressing those questions? References?

**Comment by dleutnant** [comment]
How about setting a package option `influxdbr.show_progress` (TRUE/FALSE) to control progress bar?

**Comment by dleutnant** [comment]
s. b14c6d605d8817797e52fffe2ca48864de0bc68d
