### ISSUE TITLE
Don't split the entire data internally

### ISSUE THREAD

**Issue by vspinu** [dleutnant/influxdbr#52]
For big data, splitting  essentially creates yet another copy of the input data. One can just iterate over a split index instead and create one small data.frame per itertation instead.

**Comment by dleutnant** [comment]
This indeed is a good idea. I'll dive into it.

**Comment by vspinu** [comment]
I have a working solution for this and other issues. Will pull in a few hours once sure it works as expected.

**Comment by dleutnant** [comment]
That'd be great!
