### ISSUE TITLE
cannot write data.tables

### ISSUE THREAD

**Issue by vspinu** [dleutnant/influxdbr#53]
writing data.tables currently fails:

```R

create_database(con, "tmp")
influx_write(con = con, db = "tmp", 
             x = as.data.table(Orange),
             measurement = "tt",
             time_col = "age",
             tag_cols = "Tree")

+ Error: All arguments must be named
[90mCall `rlang::last_error()` to see a backtrace[39m
 
---------------------------------- 

34: stop(cnd) at cnd.R#388
33: abort("All arguments must be named") at vars-rename.R#12
32: tidyselect::vars_rename(.vars = vars, ..., .strict = strict) at reexport-tidyselect.R#54
31: rename_vars(vars, !!!args) at reexport-tidyselect.R#81
30: dplyr::rename_vars_(names(.data), dots) at tbl-dt.r#300
29: rename_.data.table(.data, .dots = lazyeval::lazy_dots(...)) at manip.r#507
28: rename_(.data, .dots = lazyeval::lazy_dots(...)) at tbl-dt.r#285
27: rename.data.table(.tbl, !!!syms) at manip.r#498
26: rename(.tbl, !!!syms) at colwise-select.R#49
25: dplyr::rename_all(., dplyr::funs(replace_spec_char(., chars = c(",", 
        "=", " "))))
24: function_list[[i]](value) at freduce.R#17
23: freduce(value, `_function_list`) at pipe.R#28
22: `_fseq`(`_lhs`)
21: eval(quote(`_fseq`(`_lhs`)), env, env)
20: eval(quote(`_fseq`(`_lhs`)), env, env) at pipe.R#44
19: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env)) at pipe.R#44
18: x %>% dplyr::select(dplyr::one_of(tag_cols)) %>% dplyr::rename_all(dplyr::funs(replace_spec_char(., 
        chars = c(",", "=", " ")))) %>% dplyr::mutate_all(dplyr::funs(replace_spec_char(., 
        chars = c(",", "=", " ")))) %>% purrr::imap_dfr(~paste(.y, 
        .x, sep = "=")) %>% tidyr::unite(col = "tags", dplyr::everything(), 
        sep = ",") %>% dplyr::mutate(tags = paste(",", tags, sep = "")) at influxdb_line_protocol.R#191
17: convert_to_line_protocol.data.frame(x, measurement = measurement, 
        measurement_col = measurement_col, time_col = time_col, tag_cols = tag_cols, 
        precision = precision, use_integers = use_integers) at influxdb_line_protocol.R#10
16: convert_to_line_protocol(x, measurement = measurement, measurement_col = measurement_col, 
        time_col = time_col, tag_cols = tag_cols, precision = precision, 
        use_integers = use_integers)
15: eval(lhs, parent, parent)
14: eval(lhs, parent, parent) at pipe.R#41
13: convert_to_line_protocol(x, measurement = measurement, measurement_col = measurement_col, 
        time_col = time_col, tag_cols = tag_cols, precision = precision, 
        use_integers = use_integers) %>% httr_POST(con = con, query = q, 
        body = ., endpoint = "write") %>% check_srv_comm(.)
12: .f(.x[[i]], ...) at map.R#104
11: purrr::map(., ~convert_to_line_protocol(x, measurement = measurement, 
        measurement_col = measurement_col, time_col = time_col, tag_cols = tag_cols, 
        precision = precision, use_integers = use_integers) %>% httr_POST(con = con, 
        query = q, body = ., endpoint = "write") %>% check_srv_comm(.))
10: function_list[[k]](value) at freduce.R#20
9: withVisible(function_list[[k]](value)) at freduce.R#20
8: freduce(value, `_function_list`) at pipe.R#28
7: `_fseq`(`_lhs`)
6: eval(quote(`_fseq`(`_lhs`)), env, env)
5: eval(quote(`_fseq`(`_lhs`)), env, env) at pipe.R#44
4: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env)) at pipe.R#44
3: list_of_df %>% purrr::map(~convert_to_line_protocol(x, measurement = measurement, 
       measurement_col = measurement_col, time_col = time_col, tag_cols = tag_cols, 
       precision = precision, use_integers = use_integers) %>% httr_POST(con = con, 
       query = q, body = ., endpoint = "write") %>% check_srv_comm(.)) at influxdb_write.R!QN2zUG#40
2: influx_write.data.frame(con = con, db = "tmp", x = as.data.table(Orange), 
       measurement = "tt", time_col = "age", tag_cols = "Tree") at influxdb_write.R#51
1: influx_write(con = con, db = "tmp", x = as.data.table(Orange), 
       measurement = "tt", time_col = "age", tag_cols = "Tree")
````

<details>
----
devtools::session_info()
─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                                             
 version  R Under development (unstable) (2018-12-01 r75733)
 os       Ubuntu 18.04.1 LTS                                
 system   x86_64, linux-gnu                                 
 ui       X11                                               
 language                                                   
 collate  en_GB.UTF-8                                       
 ctype    en_GB.UTF-8                                       
 tz       Asia/Shanghai                                     
 date     2019-02-28                                        

─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────
 package              * version    date       lib source                                
 assertthat             0.2.0      2017-04-11 [1] CRAN (R 3.5.0)                        
 backports              1.1.2      2017-12-13 [1] CRAN (R 3.5.0)                        
 bindr                  0.1.1      2018-03-13 [1] CRAN (R 3.5.0)                        
 bindrcpp               0.2.2      2018-03-29 [1] CRAN (R 3.5.0)                        
 callr                  3.0.0.9002 2018-12-03 [1] Github (r-lib/callr@1cbce9d)          
 cli                    1.0.1      2018-09-25 [1] CRAN (R 3.6.0)                        
 crayon                 1.3.4      2017-09-16 [1] CRAN (R 3.5.0)                        
 curl                   3.2        2018-03-28 [1] CRAN (R 3.5.0)                        
 data.table           * 1.11.9     2018-12-03 [1] Github (Rdatatable/data.table@e6913a4)
 desc                   1.2.0      2018-05-01 [1] CRAN (R 3.6.0)                        
 devtools               2.0.1.9000 2018-12-03 [1] Github (r-lib/devtools@a6bbe87)       
 digest                 0.6.18     2018-10-10 [1] CRAN (R 3.6.0)                        
 dplyr                * 0.7.8      2018-11-10 [1] CRAN (R 3.6.0)                        
 dtplyr               * 0.0.2      2017-04-21 [1] CRAN (R 3.5.0)                        
 dtw                  * 1.20-1     2018-05-18 [1] CRAN (R 3.6.0)                        
 dygraphs             * 1.1.1.6    2018-07-11 [1] CRAN (R 3.6.0)                        
 fs                     1.2.6      2018-08-23 [1] CRAN (R 3.6.0)                        
 glue                   1.3.0      2018-07-17 [1] CRAN (R 3.6.0)                        
 htmltools              0.3.6      2017-04-28 [1] CRAN (R 3.5.0)                        
 htmlwidgets            1.3        2018-09-30 [1] CRAN (R 3.6.0)                        
 httr                   1.4.0      2018-12-11 [1] CRAN (R 3.6.0)                        
 IBrokers             * 0.9-12     2014-09-22 [1] CRAN (R 3.6.0)                        
 influxdbr            * 0.14.2     2019-02-28 [1] local                                 
 jsonlite               1.6        2018-12-07 [1] CRAN (R 3.6.0)                        
 lattice                0.20-38    2018-11-04 [2] CRAN (R 3.6.0)                        
 lazyeval               0.2.1      2017-10-29 [1] CRAN (R 3.5.0)                        
 lightgbm             * 2.2.3      2019-01-10 [1] local                                 
 lubridate            * 1.7.4      2018-12-03 [1] local                                 
 magrittr               1.5        2014-11-22 [1] CRAN (R 3.5.0)                        
 memoise                1.1.0      2017-04-21 [1] CRAN (R 3.5.0)                        
 PerformanceAnalytics * 1.5.2      2018-03-02 [1] CRAN (R 3.6.0)                        
 pillar                 1.3.1      2018-12-15 [1] CRAN (R 3.6.0)                        
 pkgbuild               1.0.2.9000 2018-12-03 [1] Github (r-lib/pkgbuild@6e4ebdf)       
 pkgconfig              2.0.2      2018-08-16 [1] CRAN (R 3.6.0)                        
 pkgload                1.0.1.9000 2018-12-03 [1] Github (r-lib/pkgload@0ef4f58)        
 prettyunits            1.0.2      2015-07-13 [1] CRAN (R 3.5.0)                        
 processx               3.2.0.9001 2018-12-03 [1] Github (r-lib/processx@366475b)       
 progress             * 1.1.2      2016-12-14 [1] CRAN (R 3.5.0)                        
 proxy                * 0.4-22     2018-04-08 [1] CRAN (R 3.6.0)                        
 ps                     1.2.1      2018-11-06 [1] CRAN (R 3.6.0)                        
 purrr                * 0.2.5      2018-05-29 [1] CRAN (R 3.6.0)                        
 quadprog               1.5-5      2013-04-17 [1] CRAN (R 3.5.0)                        
 quantmod             * 0.4-13     2018-04-13 [1] CRAN (R 3.6.0)                        
 R6                   * 2.4.0      2019-02-14 [1] CRAN (R 3.6.0)                        
 Rcpp                   1.0.0      2018-11-07 [1] CRAN (R 3.6.0)                        
 RcppRoll             * 0.2.2      2015-04-05 [1] CRAN (R 3.5.0)                        
 remotes                2.0.2.9000 2018-12-03 [1] Github (r-lib/remotes@2e3bf35)        
 rlang                  0.3.1.9000 2019-02-19 [1] Github (r-lib/rlang@7243c6d)          
 rprojroot              1.3-2      2018-01-03 [1] CRAN (R 3.5.0)                        
 rvest                * 0.3.2      2016-06-17 [1] CRAN (R 3.6.0)                        
 sessioninfo            1.1.1      2018-11-05 [1] CRAN (R 3.6.0)                        
 stringdist           * 0.9.4.6    2017-07-31 [1] CRAN (R 3.5.0)                        
 testthat               2.0.0      2017-12-13 [1] CRAN (R 3.5.0)                        
 tibble                 1.4.2      2018-01-22 [1] CRAN (R 3.5.0)                        
 tidyr                  0.8.2      2018-10-28 [1] CRAN (R 3.6.0)                        
 tidyselect           * 0.2.5      2018-10-11 [1] CRAN (R 3.6.0)                        
 TTR                  * 0.23-3     2018-01-24 [1] CRAN (R 3.5.0)                        
 usethis                1.4.0      2018-08-14 [1] CRAN (R 3.6.0)                        
 VSR                  * 0.0.0.9000 2019-01-11 [1] local                                 
 withr                  2.1.2.9000 2018-10-23 [1] Github (jimhester/withr@be57595)      
 xml2                 * 1.2.0.9000 2018-12-18 [1] Github (hadley/xml2@de9781d)          
 xts                  * 0.10-1     2017-12-20 [1] CRAN (R 3.5.0)                        
 zoo                  * 1.8-1      2018-01-08 [1] CRAN (R 3.5.0)                        

[1] /home/vspinu/.lib/3.6.0
[2] /home/vspinu/bin/R-latest/library
> 

</details>

**Comment by dleutnant** [comment]
I haven't officially tested the support of `data.table` objects but the dummy query below shows no issues. Can you share your dataset or do you have anything else that I can use to reproduce your issue?

``` r
library(magrittr)
  
  # create dummy data.table
  dt <- data.table::data.table(time = seq(from = Sys.time(), by = "-5 min", length.out = 10),
                               `tag_one,` = sample(LETTERS[1:5], 10, replace = T),
                               tag_two = sample(LETTERS[1:5], 10, replace = T),
                               `tag three` = sample(paste(LETTERS[1:5], "tag"), 10, replace = T),
                               field_chr = sample(paste(" ", LETTERS[1:5], "field"), 10, replace = T),
                               field_float = stats::runif(10),
                               field_int = sample(1:100000000,10),
                               field_bool = stats::runif(10) > 0.5, 
                               measurement = rep(c("one", "two", "three", "four", "five"), 2)) %>% 
    data.table::setorder("time")
    
  # connection object
  con <- influxdbr::influx_connection(group = "admin")
#> Success: (204) No Content
  
  # write data.table
  influxdbr::influx_write(x = dt, 
                          con = con,
                          db = "test",
                          measurement_col = "measurement",
                          time_col = "time",
                          tag_cols = c("tag_one,", "tag_two", "tag three"),
                          use_integers = TRUE)
  
  res <-
    influxdbr::influx_query(
      con = con,
      db = "test",
      query = paste("select * from", 
                    c("one", "two", "three", "four", "five"), 
                    "group by *", collapse = ";"),
      return_xts = FALSE
    )
  
  res
#> [[1]]
#> # A tibble: 4 x 11
#>   statement_id series_names series_partial `tag three` `tag_one,` tag_two
#>          <int> <chr>        <lgl>          <chr>       <chr>      <chr>  
#> 1            0 one          FALSE          A tag       E          A      
#> 2            0 one          FALSE          B tag       A          E      
#> 3            0 one          FALSE          C tag       A          D      
#> 4            0 one          FALSE          D tag       B          A      
#> # … with 5 more variables: time <dttm>, field_bool <lgl>, field_chr <chr>,
#> #   field_float <dbl>, field_int <dbl>
#> 
#> [[2]]
#> # A tibble: 4 x 11
#>   statement_id series_names series_partial `tag three` `tag_one,` tag_two
#>          <int> <chr>        <lgl>          <chr>       <chr>      <chr>  
#> 1            1 two          FALSE          A tag       C          B      
#> 2            1 two          FALSE          A tag       E          D      
#> 3            1 two          FALSE          C tag       B          D      
#> 4            1 two          FALSE          E tag       B          E      
#> # … with 5 more variables: time <dttm>, field_bool <lgl>, field_chr <chr>,
#> #   field_float <dbl>, field_int <dbl>
#> 
#> [[3]]
#> # A tibble: 4 x 11
#>   statement_id series_names series_partial `tag three` `tag_one,` tag_two
#>          <int> <chr>        <lgl>          <chr>       <chr>      <chr>  
#> 1            2 three        FALSE          A tag       A          E      
#> 2            2 three        FALSE          B tag       D          E      
#> 3            2 three        FALSE          D tag       A          D      
#> 4            2 three        FALSE          D tag       C          A      
#> # … with 5 more variables: time <dttm>, field_bool <lgl>, field_chr <chr>,
#> #   field_float <dbl>, field_int <dbl>
#> 
#> [[4]]
#> # A tibble: 4 x 11
#>   statement_id series_names series_partial `tag three` `tag_one,` tag_two
#>          <int> <chr>        <lgl>          <chr>       <chr>      <chr>  
#> 1            3 four         FALSE          D tag       C          B      
#> 2            3 four         FALSE          E tag       A          D      
#> 3            3 four         FALSE          E tag       B          B      
#> 4            3 four         FALSE          E tag       E          D      
#> # … with 5 more variables: time <dttm>, field_bool <lgl>, field_chr <chr>,
#> #   field_float <dbl>, field_int <dbl>
#> 
#> [[5]]
#> # A tibble: 4 x 11
#>   statement_id series_names series_partial `tag three` `tag_one,` tag_two
#>          <int> <chr>        <lgl>          <chr>       <chr>      <chr>  
#> 1            4 five         FALSE          A tag       B          E      
#> 2            4 five         FALSE          B tag       E          B      
#> 3            4 five         FALSE          C tag       A          D      
#> 4            4 five         FALSE          E tag       E          E      
#> # … with 5 more variables: time <dttm>, field_bool <lgl>, field_chr <chr>,
#> #   field_float <dbl>, field_int <dbl>
```

<sup>Created on 2019-02-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by vspinu** [comment]
Strange. I posted a reproducible example with the Orange dataset. Don't you see it with my example? 

The dev versions of some libraries which I use (rlang in particular) might be the culprit here. Will dig further.

**Comment by dleutnant** [comment]
Unfortunately, I can't see the Orange dataset. Would you mind to post it again?

**Comment by vspinu** [comment]
Orange dataset is part of core R's datasets package, sorry for not being clear about that. But nevermind, it turned to be an issue in upstream [dtplyr](https://github.com/hadley/dtplyr/issues/65).

**Comment by vspinu** [comment]
But, I have to admit that this small library has a rather thick dependency list. I think such interfacing libraries should be as lightweight as possible. Nothing in the current code strictly requires dplyr.

**Comment by dleutnant** [comment]
Ok, thanks for clarifiying.

Well, the dependency list is indeed quite heavy but I simply hadn't had the time to simplify the code basis in terms of base R commands. I'll open an issue to track changes with this respect.
