### ISSUE TITLE
influx_query does not permit chunked or chunk_size options to be included

### ISSUE THREAD

**Issue by ckatsulis** [dleutnant/influxdbr#7]
In order to override db defaults on query, exposing the parameters `chunked` and `chunk_size` will allow  users to have such control over non default query settings.

This fix would have two parts:
1. Including those parameters works on inception so long as `chunked=true` and `chunk_size=n` where `n` is larger than your data set of query `LIMIT`.  If that is not the case, the `partial=true ` result in the json object will result in an error currently.
2. Modifying the json parse to deal with partial chunks (`partial=true `) will finalize the feature for behavior as influxdb intends.

**Comment by dleutnant** [comment]
Thanks @ckatsulis for your contribution. I'm planning to release an updated version of the influxbdr package by March (also to CRAN) which certainly addresses chunking options.

**Comment by dleutnant** [comment]
new influx_query takes care of InfluxDB chunking -> [dleutnant/prepare_cran](https://github.com/dleutnant/influxdbr/tree/prepare_cran)
