### ISSUE TITLE
How to close a connection?

### ISSUE THREAD

**Issue by CrisBMoya** [dleutnant/influxdbr#70]
Once a connection to the DB is open is there a way to close it?

There's the command `influx_connection()` but apparently there's no way to close such connection. It could be dangerous when there are massive open connections.

Thanks!

**Comment by dleutnant** [comment]
Hi @CrisBMoya,
we are using InfluxDB's REST api instead of a direct database access. Therefore, closing a connection is not required as there is no permanently open connection.
