### ISSUE TITLE
Undocumented feature - "series_partial"

### ISSUE THREAD

**Issue by ghost** [dleutnant/influxdbr#74]
Hi

I'm using the influxdbr version 0.14.2 on Windows. When I retrieve data as xts, there's a series not in the query called `series_partial`. I haven't found documentation for it, and the code has no comments about its intention. Can you please clarify?

Thanks

Jason

**Comment by dleutnant** [comment]
`series_partial` is a logical value returned by InfluxDB to indicate if the response has been truncated. A truncated series might be  returned due to chunking or the InfluxDB setup has a `max-row-limit` configured.

**Comment by renrutnosaj** [comment]
Thanks!
