### ISSUE TITLE
Move debugging output from "print" to "message"

### ISSUE THREAD

**Issue by ckatsulis** [dleutnant/influxdbr#8]
Is it possible to include the debugging lines as system messages or warnings rather than print statements?
I am currently using this package within an application that will not log print commands, but does have control over output from message, warning, and error handling.

**Comment by dleutnant** [comment]
To which line(s) do you refer to? Actually, I'm about to remove those lines after some testing.

**Comment by dleutnant** [comment]
debugging lines are now fully removed in latest push -> [dleutnant/prepare_cran](https://github.com/dleutnant/influxdbr/tree/prepare_cran)
